### ISSUE TITLE
A user shouldn't be allowed to change its name to ""

### ISSUE THREAD

**Issue by ZaninAndrea** [IglooCloud/IglooServer#53]
Add a check that `args.displayName` isn't empty in the [user mutation handler](https://github.com/IglooCloud/IglooServer/blob/aa2e30d366eca84848a4394158c38570178b3191/graphql/resolvers/Mutation.js#L996)

**Comment by Apoorva-13** [comment]
can i try this?

**Comment by ZaninAndrea** [comment]
Of course 👍

**Comment by Apoorva-13** [comment]
![image](https://user-images.githubusercontent.com/31508100/46580091-b8f8e280-ca3b-11e8-80b9-f2051640fe67.png)

is this correct?
if(!args.displayName || args.displayName==" ")
{
       reject('displayName required')
       return
}

**Comment by ZaninAndrea** [comment]
We are ok with `displayName` not being passed, we handle that as a "keep it as it is", but we don't want to have empty `displayName`s, you should only check that `args.displayName` isn't null nor empty.

As error message "displayName cannot be null or empty" would be more consistent with our other error messages.

If you could change those 2 things that would be perfect 🤖

**Comment by Apoorva-13** [comment]
pls let me know if this is correct or i have not understood.
is this correct?

if(args.displayName===null || args.displayName===" ")
{
  reject('displayName cannot be null or empty')
  return
}
I have to add this check here?
![image](https://user-images.githubusercontent.com/31508100/46580679-1b0b1500-ca47-11e8-90c6-580cc29b0e9b.png)

**Comment by ZaninAndrea** [comment]
You put a space between the "" (we only need to check that the string isn't completely empty), other than that it's perfect.

The place to add the check is correct

**Comment by ZaninAndrea** [comment]
Perfect, thank you for your time @Apoorva-13

**Comment by Apoorva-13** [comment]
> Perfect, thank you for your time @Apoorva-13

Your Welcome  and Thanks for the guidance !!
