### ISSUE TITLE
Rename relevance to visibility

### ISSUE THREAD

**Issue by ZaninAndrea** [IglooCloud/IglooServer#59]
Replace `relevance` with `visibility` throughout the repository.

**Comment by pantharshit00** [comment]
I am claiming this

**Comment by ZaninAndrea** [comment]
Thank you for your work, there are still to update the files `types.graphql` and `databaseDefinition.js` if anyone is up for that, will merge when all files are done.

P.S. `ValueRelevance` should also be renamed to `ValueVisibility`

**Comment by pantharshit00** [comment]
@ZaninAndrea I have done those as well have a look in the PR

**Comment by ZaninAndrea** [comment]
Sorry, didn't see the first commit. Thanks again, I'll merge the pull request then
